version: '3'
services:
  app:
    container_name: 'docker-noode-mongo'
    ports:
      - '80:3000'
    restart: always
    build: .
    links:
      - 'mongo'
  mongo:
    container_name: "mongo"
    ports:
      - '27017:27017'
    image: 'mongo'